### ISSUE TITLE
move Slim.LiveReload code into own repository

### ISSUE THREAD

**Issue by greergan** [greergan/slim.generator#12]
- [ ] greergan/slim.generator#13
- [ ] greergan/slim.livereload#2
  - [ ] greergan/slim.livereload#1
